---
- name: Update repositories on Ubuntu
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install HA Proxy on Ubuntu 
  apt:
    name: haproxy
    state: present
  when: ansible_distribution == 'Ubuntu'
  ...